project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "NCEAS Scientific Computing"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/NCEAS/scicomptasks
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - staff.qmd
      - pkgs.qmd
      - workshops.qmd
      - best_practices.qmd
    right:
      - icon: github
        href: https://github.com/NCEAS/scicomptasks
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer: |
    <img src="images/nceas_logo_square.png" width="40%"/>

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
